baseURL: "https://valentinaanthonio.github.io/"
languageCode: "en-us"
title: "Valentina Anthonio"
theme: hugo-profile

Paginate: 3
disqusShortname: 
googleAnalytics: G-NXJWC518XW

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
      
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
  #  - identifier: dropdown
  #    title: Example dropdown menu
  #    name: Dropdown
  #   weight: 2
  #  - identifier: dropdown1
  #    title: example dropdown 1
  #    name: example 1
  #    url: /#
  #    parent: dropdown
  #    weight: 1
  #  - identifier: dropdown2
  #    title: example dropdown 2
  #    name: example 2
  #    url: /#
  #    parent: dropdown
  #    weight: 2

params:
  title: "Valentina Anthonio's Profile"
  description: Welcome to my site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Valentina."
    subtitle: "I'm a Chartered Accountant and A Data Scientist "
    content: "'Every taste, every sensation, every possible pleasure is already present in the timeless awareness that is beating my heart. What use in chasing dreams that have already come true.' - Nirmala "
    image: /images/img.jpg
    button:
      enable: true
      name: "Resume"
      url: "/resume/ds_resume.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/valentinaanthonio
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/valentina-anthonio/
      #customIcons:
       # - icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/img.jpg"
    content: |-
      I'm a Chartered Accountant and a Data Scientist who enjoys finding the simplicity in the complex world. 
      I have a passion for learning new things and finding ways to share my experience and thoughts with others whiles also 
      learning from them. Currently a lecturer at Rennes School of Business in the Finance and Accounting department.
      I lecture students in Program Grade Ecole (PGE) 1 and 3(Masters) levels. I also take time to work on 
      some machine learning projects from time to time while also freelancing in audit and other consulting jobs. before this, 
      I did my internship with the Ghana Armed forces in the budget and finance section, worked as a senior audit associate with Mazars, 
      General manager with millennium mart limited (Subcontractor of Vivo Energy limited (Shell Licensee for the African Market)) 
      and subsequently as a Senior Consultant with AAA Excel Ghana Limited.
      I also freelanced as an audit manager for the Ghana National Health Insurance Authority and JK Horgle Transport Company.
      After years of working, I traveled to France to pursue my MBA at Rennes School of Business, where I currently lecture. 

      J'aime nager, lire, chanter et cuisiner. Je l'aime et je suis toujours très heureux. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "TenseorFlow"
        - "Sklearn"
        - "Python"
        - "SQL"
        - "Tableau"
        - "Power BI"
        - "Python Panel"

  # Experience
  experience:
    enable: true
    items:
      - job: "Finance and Accounting Lecturer"
        company: "Rennes School of Business"
        date: "Jan 2020- present"
        content: |
          - I am currently working as a lecturer in the finance and accounting department.
          - Reviewed and recommended updates to teaching materials and methods to enhance creativity and productivity.
          - Accelerated the culture of acceptance of divergent views and culture appreciation among students.
      - job: "Freelance Audit Manager"
        company: "National Health Insurance Authority - Ghana"
        date: "Feb 2016 - Mar 2017"
        content: |
         - Recoveried over $1 million in over payments and taxes for the authority.
         - Reviewed and made recommendations on service providers contracts renewal.

      - job: "Senior Consultant"
        company: "AAA Excel Ghana Limited"
        date: "Mar 2016 - jan 2018"
        content: |
          -	Spearheaded the design and negotiations of financing facilities which reduced overall cost for clients by 8%.
          - Collaborated and transformed client’s business outlook and processed by 5%+.
          - Performed stress tests on clients’ portfolios and devised new methodologies to grow performance by 10%.

      - job: "General Manager Finance and Admin"
        company: "Millennium Mart Limited"
        date: "Jan 2013 - Mar 2016"
        info:
          enable: false
        content: |
          -	Earned 2 awards for high performing outlets in west Africa for two consecutive years

          -	Managed 12 cross functional managers to Increase the performance and profitability of the company by 40%. 
          -Designed and implemented efficient internal control systems that reduced risk of fraud to 0%.


      - job: "Senior Audit Associate"
        company: "Mazars"
        date: "Augut 2009 - Jan 2013"
        featuredLink:
          enable: false 
          url: "https://example.com"
        content: |
          •	Managed teams of 4 to 7 members in the execution of different audits and other tasks.

          - Liaised with key stakeholders in reviewing clients’ strategic needs and making appropriate recommendations.
          - Led and trained new audit trainees (5-20) during integration and on the use of the audit software.

      
  # Education
  education:
    enable: true
    items:
      - title: "Machine Learning Engineering and Operations"
        school:
          name: "DeepLearning AI"
        date: "2022 - 2022"
        content: |-
         - Build Data Pipelines.
         - Establish a model baseline, address concept drift, and prototype how to develop, deploy, and continuously improve a productionized ML application
          
      - title: "TensorFlow Advanced Techniques"
        school:
          name: "DeepLearning AI"
        date: "2022 - 2022"
        content: |-
          - Tensorflow Functional API
          - Building custom loss function 
          - Object detection 
      - title: "TensorFlow Developer Professional Certificate"
        school:
          name: "DeepLearning AI"
        date: "2022 - 2022"
        content: |-
          - Apply RNNs, GRUs, and LSTMs to train text repositories.
          - Develop strategies to handle prevent overfitting.
      - title: "Deep Learning Specialization"
        school:
          name: "DeepLearning AI"
        date: "2022 - 2022"
        content: |-
          - Build and train RNNs, work with NLP and Word Embeddings.
          - Transformers and vectorised neural networks implementation.
      - title: "Data Analyst NanoDegree"
        school: 
          name: "Udacity"
        date: "2022 - 2022"
        content: |-
          - Apply data wrangling and mining skills to exract and work on data.
          - Apply A/B testing on real world data.
      - title: "Data Science"
        school: 
          name: "Practicum by Yandex"
        date: "2021 - 2022"
        content: |-
         - Machine learning and deep learning models.
          
      - title: "Data Analytics"
        school: 
          name: "Google"
        date: "2020 - 2021"
        content: |- 
         - Data Cleaning, analysis and visualisation.
         
      - title: "Financial Modeling and Valuation Analyst"
        school:
          name: "Corporate Finance Institute"
        date: "2020 - 2020"
        content: |-
          - Business valuation Techniques.

      - title: "Master of Business Administration"
        school:
          name: "Rennes School of Business"
        date: "2018 - 2020"
        content: |-
          - Specialisation in Innovation and Enterpreneuership
          - Consulting project for Groupe AIM - Tier 1 car manufacturing company.
            
      - title: "Chartered Accountant"
        school:
          name: "Association of Chartered Certified Accountants"
        date: "2008 - 2012"
        content: |-
          Specialisation in: 
          - Advance Financial management
          - Advanced Performance Mangement


  # projects
  projects:
    enable: true
    items:
      - title: Telecom Interconnet
        content: Use Maching learning model to forecast churn clients. Provide promotional activities to clients who are likely cancel their contract.
        image: /images/projects/telecom.png
        featured:
        links:
          - icon: fab fa-github
            url: https://github.com/valentinaanthonio/Telecom-operator-Interconnect-/blob/main/sprint_final_project.ipynb
         
      - title: Zefra Gold Recovery 
        content: Checked how different metals change depending on purification stage and with custom evaluation metric, model and evaluate the trained models.
        image: /images/projects/gold.png
        links:
          - icon: fab fa-github
            url: https://github.com/valentinaanthonio/Gold-recovery-project/blob/main/sprint_10_integrated_project_2.ipynb

      - title: Swift Lift Taxi
        content: A time series analysis on predicting the amount of taxi orders for the next hour.
        image: /images/projects/taxi.png
        links:
          - icon: fab fa-github
            url: https://github.com/valentinaanthonio/Time-Series-Forcasting/blob/main/sprint_13_time_series_project.ipynb

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: eseyram64@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/valentinaanthonio
      linkedin: https://www.linkedin.com/in/valentina-anthonio/
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com
